api:
  host: '0.0.0.0'
  port: 8080
  writeTimeout: 15
  readTimeout: 15
  idleTimeout: 60
database:
  connectionString: "postgres://user:password@localhost:5432/weather_notification?sslmode=disable"
broker:
  connectionURL: "amqp://rabbitmq:rabbitmq@localhost:5672/"
weatherAPI:
  addressURL: "http://servicos.cptec.inpe.br"
  timeout: 300
  retries: 5
websocket:
  client:
    host: '0.0.0.0'
    port: 9090
    writeTimeout: 15
    readTimeout: 15
    idleTimeout: 60